# Site settings
title: CryptoTactics'
email: luis@cryptocatics.com
description: > # this means to ignore newlines until "baseurl:"
  Public blog with some personal notes on several tech subjects. Infosec, programming, unix and so on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cryptotactics.com" # the base hostname & protocol for your site
twitter_username: ah_et_tal
github_username:  ahettal

# Build settings
markdown: kramdown
